/**
 * Shared Resolver Compiler
 *
 * Compiles TypeScript AppSync resolvers to JavaScript:
 * - Discovers resolver files in backend/resolvers
 * - Inlines gqlTypes and schema imports
 * - Transforms enums to const objects (AppSync compatibility)
 * - Validates with AppSync EvaluateCode API
 * - Uploads to S3 with content-based hash
 * - Cleans up old deployments
 *
 * Used by ALL projects with AppSync GraphQL APIs
 */

import { execSync } from "child_process";
import * as fsPromises from "fs/promises";
import * as fsNode from "fs";
import * as path from "path";
import {
  S3Client,
  PutObjectCommand,
  ListObjectsV2Command,
  DeleteObjectsCommand,
} from "@aws-sdk/client-s3";
import {
  AppSyncClient,
  EvaluateCodeCommand,
  EvaluateCodeCommandInput,
} from "@aws-sdk/client-appsync";
import * as crypto from "crypto";
import type { Logger } from "./types";

interface ExecError {
  message?: string;
  stdout?: Buffer | string;
  stderr?: Buffer | string;
  stack?: string;
}

export interface ResolverCompilerConfig {
  logger: Logger;
  projectRoot: string; // Path to project root (e.g., /home/user/dev/work-stay)
  appName: string; // e.g., "helpstay", "quiz-night-live"
  stage: string; // e.g., "dev", "prod"
  region: string; // AWS region
  s3BucketName: string; // Template bucket name
  s3KeyPrefix?: string; // S3 key prefix (default: "resolvers")
  tableName?: string; // DynamoDB table name (default: ${appName}-datatable-${stage})
  resolverFiles?: string[]; // Optional explicit list of resolver files
}

/**
 * Resolver Compiler
 *
 * Compiles TypeScript resolvers to JavaScript for AppSync
 */
export class ResolverCompiler {
  private logger: Logger;
  private projectRoot: string;
  private buildDir: string;
  private appName: string;
  private stage: string;
  private region: string;
  private s3BucketName: string;
  private s3KeyPrefix: string;
  private tableName: string;
  private resolverFiles: string[];
  private s3Client: S3Client;
  private appSyncClient: AppSyncClient;

  constructor(config: ResolverCompilerConfig) {
    this.logger = config.logger;
    this.projectRoot = config.projectRoot;
    this.appName = config.appName;
    this.stage = config.stage;
    this.region = config.region;
    this.s3BucketName = config.s3BucketName;
    this.s3KeyPrefix = config.s3KeyPrefix || "resolvers";
    this.tableName =
      config.tableName || `${config.appName}-datatable-${config.stage}`;
    this.resolverFiles = config.resolverFiles || [];
    this.s3Client = new S3Client({ region: this.region });
    this.appSyncClient = new AppSyncClient({ region: this.region });
    this.buildDir = path.join(this.projectRoot, ".cache", "deploy", "resolvers");
  }

  /**
   * Discover resolver files if not provided
   */
  public async discoverResolverFiles(): Promise<string[]> {
    if (this.resolverFiles.length > 0) {
      return this.resolverFiles;
    }

    const resolverDir = path.join(this.projectRoot, "backend", "resolvers");
    const files: string[] = [];

    const findResolvers = (dir: string, relativePath: string = ""): void => {
      const entries = fsNode.readdirSync(dir, { withFileTypes: true });
      for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);
        const relPath = relativePath
          ? path.join(relativePath, entry.name)
          : entry.name;
        if (entry.isDirectory()) {
          findResolvers(fullPath, relPath);
        } else if (
          entry.name.endsWith(".ts") &&
          !entry.name.includes(".test.") &&
          !entry.name.includes(".spec.")
        ) {
          files.push(relPath);
        }
      }
    };

    findResolvers(resolverDir);
    this.resolverFiles = files;
    return files;
  }

  /**
   * Add header comment to compiled JS
   */
  private addHeaderToJs(jsContent: string, sourceFilePath: string): string {
    const relativeSourcePath = path.relative(this.projectRoot, sourceFilePath);
    const header = `
/**********************************************************************************************************************
 *  DO NOT EDIT THIS FILE. Automatically generated by the build process.                                              *
 *  Source file: ${relativeSourcePath}
 **********************************************************************************************************************/
    `;
    return header.trim() + "\n\n" + jsContent;
  }

  /**
   * Upload file to S3
   */
  private async uploadToS3(
    s3Key: string,
    content: string,
    contentType: string
  ): Promise<void> {
    await this.s3Client.send(
      new PutObjectCommand({
        Bucket: this.s3BucketName,
        Key: s3Key,
        Body: content,
        ContentType: contentType,
      })
    );
  }

  /**
   * Validate resolver code with AppSync
   */
  private async validateWithAppSync(
    code: string,
    resolverName: string
  ): Promise<boolean> {
    // Skip validation for pipeline functions
    const isPipeline = resolverName.includes(".pipeline.");
    if (isPipeline) {
      return true;
    }

    const hasRequest =
      code.includes("export function request") ||
      code.includes("export { request");
    const hasResponse =
      code.includes("export function response") ||
      code.includes("export { response");

    const minimalContext = JSON.stringify({
      arguments: {},
      args: {},
      identity: {
        sub: "test-user",
        claims: { "cognito:groups": [] },
        groups: [],
      },
      source: {},
      result: {},
      prev: { result: {} },
      stash: {},
      request: { headers: {} },
    });

    try {
      if (hasRequest) {
        const requestInput: EvaluateCodeCommandInput = {
          runtime: { name: "APPSYNC_JS", runtimeVersion: "1.0.0" },
          code,
          context: minimalContext,
          function: "request",
        };
        const requestResult = await this.appSyncClient.send(
          new EvaluateCodeCommand(requestInput)
        );
        if (requestResult.error) {
          throw new Error(
            `AppSync validation failed for ${resolverName} (request): ${requestResult.error.message}`
          );
        }
      }

      if (hasResponse) {
        const responseInput: EvaluateCodeCommandInput = {
          runtime: { name: "APPSYNC_JS", runtimeVersion: "1.0.0" },
          code,
          context: minimalContext,
          function: "response",
        };
        const responseResult = await this.appSyncClient.send(
          new EvaluateCodeCommand(responseInput)
        );
        if (responseResult.error) {
          throw new Error(
            `AppSync validation failed for ${resolverName} (response): ${responseResult.error.message}`
          );
        }
      }

      this.logger.debug(`Validation passed: ${resolverName}`);
      return true;
    } catch (error: unknown) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);

      // Ignore outdated lint rules that AppSync no longer enforces
      const outdatedLintRules = [
        "@aws-appsync/no-function-passing",
        "ArrowFunction",
      ];
      const isOutdatedLintRule = outdatedLintRules.some((rule) =>
        errorMessage.includes(rule)
      );
      if (isOutdatedLintRule) {
        return true;
      }

      // Check for truly unsupported patterns
      const trulyUnsupportedPatterns = [
        "@aws-appsync/no-for",
        "@aws-appsync/no-while",
        "@aws-appsync/no-disallowed-unary-operators",
      ];
      const isTrulyUnsupported = trulyUnsupportedPatterns.some((pattern) =>
        errorMessage.includes(pattern)
      );

      if (
        isTrulyUnsupported ||
        errorMessage.includes("code contains one or more errors") ||
        errorMessage.includes("SyntaxError")
      ) {
        throw new Error(
          `AppSync code validation failed for ${resolverName}: ${errorMessage}`
        );
      }

      // Runtime errors during evaluation are OK - the code syntax is valid
      return true;
    }
  }

  /**
   * Cleanup old S3 resolver deployments
   */
  private async cleanupOldS3Resolvers(keepCount: number = 5): Promise<void> {
    try {
      const prefix = path.posix.join(this.s3KeyPrefix, this.stage) + "/";
      const listCommand = new ListObjectsV2Command({
        Bucket: this.s3BucketName,
        Prefix: prefix,
        Delimiter: "/",
      });

      const response = await this.s3Client.send(listCommand);

      if (!response.CommonPrefixes || response.CommonPrefixes.length === 0) {
        return;
      }

      const hashDirs: { prefix: string; hash: string }[] = [];
      for (const commonPrefix of response.CommonPrefixes) {
        if (commonPrefix.Prefix) {
          const hash = commonPrefix.Prefix.replace(prefix, "").replace("/", "");
          if (hash) {
            hashDirs.push({ prefix: commonPrefix.Prefix, hash });
          }
        }
      }

      const hashDirsWithTime: {
        prefix: string;
        hash: string;
        lastModified: Date;
      }[] = [];
      for (const hashDir of hashDirs) {
        const listObjectsCommand = new ListObjectsV2Command({
          Bucket: this.s3BucketName,
          Prefix: hashDir.prefix,
          MaxKeys: 1,
        });
        const objectsResponse = await this.s3Client.send(listObjectsCommand);
        if (
          objectsResponse.Contents &&
          objectsResponse.Contents.length > 0
        ) {
          const lastModified =
            objectsResponse.Contents[0].LastModified || new Date(0);
          hashDirsWithTime.push({ ...hashDir, lastModified });
        }
      }

      hashDirsWithTime.sort(
        (a, b) => b.lastModified.getTime() - a.lastModified.getTime()
      );
      const deploymentsToDelete = hashDirsWithTime.slice(keepCount);

      if (deploymentsToDelete.length === 0) return;

      for (const deployment of deploymentsToDelete) {
        await this.deleteS3Prefix(deployment.prefix);
      }

      this.logger.info(
        `Cleaned up ${deploymentsToDelete.length} old resolver deployment(s)`
      );
    } catch (error: unknown) {
      const err = error as ExecError;
      this.logger.warning(
        `Could not cleanup old S3 resolvers: ${err.message || String(error)}`
      );
    }
  }

  /**
   * Delete all objects under S3 prefix
   */
  private async deleteS3Prefix(prefix: string): Promise<void> {
    let continuationToken: string | undefined;

    do {
      const listCommand = new ListObjectsV2Command({
        Bucket: this.s3BucketName,
        Prefix: prefix,
        ContinuationToken: continuationToken,
      });

      const response = await this.s3Client.send(listCommand);

      if (response.Contents && response.Contents.length > 0) {
        const objectsToDelete = response.Contents.map((obj) => ({
          Key: obj.Key!,
        }));
        const deleteCommand = new DeleteObjectsCommand({
          Bucket: this.s3BucketName,
          Delete: { Objects: objectsToDelete, Quiet: true },
        });
        await this.s3Client.send(deleteCommand);
      }

      continuationToken = response.NextContinuationToken;
    } while (continuationToken);
  }

  /**
   * Setup build directory with package.json and tsconfig.json
   */
  private async setupBuildDirectory(): Promise<void> {
    await fsPromises.rm(this.buildDir, { recursive: true, force: true });
    await fsPromises.mkdir(this.buildDir, { recursive: true });

    await this.setupBuildConfiguration();

    // Try to symlink node_modules from project root
    const rootNodeModules = path.join(this.projectRoot, "node_modules");
    const buildNodeModules = path.join(this.buildDir, "node_modules");

    if (fsNode.existsSync(rootNodeModules)) {
      try {
        await fsPromises.symlink(
          rootNodeModules,
          buildNodeModules,
          "junction"
        );
        return;
      } catch {
        // Fallback to yarn install
      }
    }

    try {
      execSync(
        "yarn install --ignore-scripts --no-progress --non-interactive --prefer-offline",
        { cwd: this.buildDir, stdio: "pipe", encoding: "utf8" }
      );
    } catch (error: unknown) {
      const err = error as ExecError;
      this.logger.error(
        `Yarn install failed: ${err.message || String(error)}`
      );
      throw error;
    }
  }

  /**
   * Create package.json and tsconfig.json in build directory
   */
  private async setupBuildConfiguration(): Promise<void> {
    const packageJson = {
      name: "appsync-resolvers-build",
      version: "1.0.0",
      type: "module",
      private: true,
      dependencies: {
        "@aws-appsync/utils": "^1.1.1",
      },
      devDependencies: {
        typescript: "5.5.4",
        "@types/node": "^20.12.0",
      },
    };

    await fsPromises.writeFile(
      path.join(this.buildDir, "package.json"),
      JSON.stringify(packageJson, null, 2)
    );

    const tsConfig = {
      compilerOptions: {
        target: "ES2020",
        module: "ES6",
        moduleResolution: "node",
        outDir: "dist",
        rootDir: ".",
        removeComments: true,
        skipLibCheck: true,
        skipDefaultLibCheck: true,
        downlevelIteration: false,
        importHelpers: false,
        noEmitHelpers: true,
        strict: false,
        noImplicitAny: false,
      },
      include: ["**/*.ts"],
      exclude: [
        "node_modules",
        "dist",
        "**/__tests__",
        "**/*.test.ts",
        "**/*.spec.ts",
      ],
    };

    await fsPromises.writeFile(
      path.join(this.buildDir, "tsconfig.json"),
      JSON.stringify(tsConfig, null, 2)
    );
  }

  /**
   * Prepare source file: inline imports, add AppSync globals, inject table name
   */
  private async prepareSourceFile(
    originalCode: string,
    resolverAbsolutePath: string
  ): Promise<void> {
    const baseResolverDir = path.join(this.projectRoot, "backend", "resolvers");
    const resolverRelativePath = path.relative(
      baseResolverDir,
      resolverAbsolutePath
    );

    let codeToCompile = originalCode;

    // Handle gqlTypes imports by inlining
    const gqlTypesImportRegex =
      /import\s+(?:type\s+)?\{([^}]*)\}\s+from\s+(['"])[^'"]*gqlTypes[^'"]*\2;?\s*\n?/g;
    let gqlTypesMatch;
    const importedGqlTypes = new Set<string>();

    while ((gqlTypesMatch = gqlTypesImportRegex.exec(originalCode)) !== null) {
      const importedItems = gqlTypesMatch[1]
        .split(",")
        .map((item: string) => item.trim());
      importedItems.forEach((item: string) => {
        const cleanItem = item
          .replace(/^type\s+/, "")
          .split(/\s+as\s+/)[0]
          .trim();
        if (cleanItem) importedGqlTypes.add(cleanItem);
      });
    }

    if (importedGqlTypes.size > 0) {
      const gqlTypesSourcePath = path.join(
        this.projectRoot,
        "shared",
        "src",
        "types",
        "gqlTypes.ts"
      );

      if (!fsNode.existsSync(gqlTypesSourcePath)) {
        throw new Error(
          `gqlTypes.ts not found at: ${gqlTypesSourcePath}. Generate GraphQL types first.`
        );
      }

      let gqlTypesContent = await fsPromises.readFile(
        gqlTypesSourcePath,
        "utf-8"
      );

      // Transform enums to const objects (AppSync compatibility)
      gqlTypesContent = gqlTypesContent.replace(
        /(?:\/\*\*[\s\S]*?\*\/\s*)?export\s+enum\s+(\w+)\s*\{([^}]+)\}/g,
        (_match, enumName, enumBody) => {
          const members = enumBody
            .split(",")
            .map((m: string) => m.trim())
            .filter((m: string) => m.length > 0)
            .map((m: string) => {
              const [key, value] = m.split("=").map((s: string) => s.trim());
              if (key && value) return `  ${key}: ${value}`;
              return null;
            })
            .filter((m: string | null): m is string => m !== null);

          return `const ${enumName} = {\n${members.join(",\n")}\n} as const;\ntype ${enumName} = (typeof ${enumName})[keyof typeof ${enumName}];`;
        }
      );

      let inlinedContent = "// Inlined types from gqlTypes.ts\n";
      inlinedContent += gqlTypesContent
        .replace(/^import\s+.*from\s+['"].*['"];?\s*$/gm, "")
        .replace(/^export\s+/gm, "")
        .trim();
      inlinedContent += "\n";

      gqlTypesImportRegex.lastIndex = 0;
      codeToCompile = codeToCompile.replace(
        gqlTypesImportRegex,
        inlinedContent
      );
    }

    // Handle constants imports (e.g., from shared/src/constants/tasks.ts)
    const constantsImportRegex =
      /import\s+(?:type\s+)?\{([^}]*)\}\s+from\s+(['"])[^'"]*constants\/(\w+)[^'"]*\2;?\s*\n?/g;
    let constantsMatch;
    const constantsImports: { items: Set<string>; file: string }[] = [];

    while ((constantsMatch = constantsImportRegex.exec(codeToCompile)) !== null) {
      const importedItems = constantsMatch[1]
        .split(",")
        .map((item: string) => item.trim());
      const items = new Set<string>();
      importedItems.forEach((item: string) => {
        const cleanItem = item
          .replace(/^type\s+/, "")
          .split(/\s+as\s+/)[0]
          .trim();
        if (cleanItem) items.add(cleanItem);
      });
      if (items.size > 0) {
        constantsImports.push({ items, file: constantsMatch[3] });
      }
    }

    if (constantsImports.length > 0) {
      for (const constImport of constantsImports) {
        const constantsSourcePath = path.join(
          this.projectRoot,
          "shared",
          "src",
          "constants",
          `${constImport.file}.ts`
        );

        if (fsNode.existsSync(constantsSourcePath)) {
          let constantsContent = await fsPromises.readFile(
            constantsSourcePath,
            "utf-8"
          );

          // Remove imports from the constants file (they reference gqlTypes which will be inlined separately)
          constantsContent = constantsContent.replace(
            /^import\s+.*from\s+['"].*['"];?\s*$/gm,
            ""
          );

          // Remove exports, we're inlining
          constantsContent = constantsContent.replace(/^export\s+/gm, "");

          const inlinedConstants = `// Inlined constants from ${constImport.file}.ts\n${constantsContent.trim()}\n`;

          // Replace the first import of this file with the inlined content
          const specificImportRegex = new RegExp(
            `import\\s+(?:type\\s+)?\\{[^}]*\\}\\s+from\\s+(['"])[^'"]*constants\\/${constImport.file}[^'"]*\\1;?\\s*\\n?`
          );
          codeToCompile = codeToCompile.replace(specificImportRegex, inlinedConstants);
        }
      }

      // Remove any remaining constants imports that weren't found
      constantsImportRegex.lastIndex = 0;
      codeToCompile = codeToCompile.replace(constantsImportRegex, "");
    }

    // Handle @appname/shared/src/schemas imports (WithTypename helper and *Return types)
    const schemasImportRegex =
      /import\s+(?:type\s+)?\{([^}]*)\}\s+from\s+(['"])[^'"]*schemas[^'"]*\2;?\s*\n?/g;
    let schemasMatch;
    const importedSchemaTypes = new Set<string>();

    while ((schemasMatch = schemasImportRegex.exec(codeToCompile)) !== null) {
      const importedItems = schemasMatch[1]
        .split(",")
        .map((item: string) => item.trim());
      importedItems.forEach((item: string) => {
        const cleanItem = item
          .replace(/^type\s+/, "")
          .split(/\s+as\s+/)[0]
          .trim();
        if (cleanItem) importedSchemaTypes.add(cleanItem);
      });
    }

    if (importedSchemaTypes.size > 0) {
      const schemasSourcePath = path.join(
        this.projectRoot,
        "shared",
        "src",
        "schemas",
        "generated-returns.ts"
      );

      const returnTypeMap: Record<
        string,
        { baseType: string; typeName: string }
      > = {};

      if (fsNode.existsSync(schemasSourcePath)) {
        const schemasContent = await fsPromises.readFile(
          schemasSourcePath,
          "utf-8"
        );
        const returnTypeRegex =
          /export\s+type\s+(\w+Return)\s*=\s*WithTypename<(\w+),\s*"(\w+)">/g;
        let match;
        while ((match = returnTypeRegex.exec(schemasContent)) !== null) {
          const [, returnTypeName, baseType, typeName] = match;
          returnTypeMap[returnTypeName] = { baseType, typeName };
        }
      }

      let schemasDefinition = `// Inlined from shared/src/schemas
type WithTypename<T, TypeName extends string> = T & { __typename: TypeName };
`;

      // If gqlTypes wasn't already imported, inline it now
      if (importedGqlTypes.size === 0) {
        const gqlTypesSourcePath = path.join(
          this.projectRoot,
          "shared",
          "src",
          "types",
          "gqlTypes.ts"
        );

        if (fsNode.existsSync(gqlTypesSourcePath)) {
          let gqlTypesContent = await fsPromises.readFile(
            gqlTypesSourcePath,
            "utf-8"
          );

          gqlTypesContent = gqlTypesContent.replace(
            /(?:\/\*\*[\s\S]*?\*\/\s*)?export\s+enum\s+(\w+)\s*\{([^}]+)\}/g,
            (_match, enumName, enumBody) => {
              const members = enumBody
                .split(",")
                .map((m: string) => m.trim())
                .filter((m: string) => m.length > 0)
                .map((m: string) => {
                  const [key, value] = m
                    .split("=")
                    .map((s: string) => s.trim());
                  if (key && value) return `  ${key}: ${value}`;
                  return null;
                })
                .filter((m: string | null): m is string => m !== null);

              return `const ${enumName} = {\n${members.join(",\n")}\n} as const;\ntype ${enumName} = (typeof ${enumName})[keyof typeof ${enumName}];`;
            }
          );

          schemasDefinition += "\n// Base types from gqlTypes.ts\n";
          schemasDefinition += gqlTypesContent
            .replace(/^import\s+.*from\s+['"].*['"];?\s*$/gm, "")
            .replace(/^export\s+/gm, "")
            .trim();
          schemasDefinition += "\n";
        }
      }

      // Add type definitions for each imported Return type
      for (const importedType of importedSchemaTypes) {
        if (importedType === "WithTypename") continue;
        const mapping = returnTypeMap[importedType];
        if (mapping) {
          schemasDefinition += `type ${importedType} = WithTypename<${mapping.baseType}, "${mapping.typeName}">;\n`;
        }
      }

      schemasImportRegex.lastIndex = 0;
      codeToCompile = codeToCompile.replace(
        schemasImportRegex,
        schemasDefinition
      );
    }

    // Remove @aws-appsync/utils imports
    codeToCompile = codeToCompile.replace(
      /import\s*{\s*[^}]*\s*}\s*from\s*["']@aws-appsync\/utils["'];?\s*/g,
      ""
    );
    codeToCompile = codeToCompile.replace(
      /import\s*.*\s*from\s*["']@aws-appsync\/utils["'];?\s*/g,
      ""
    );

    // Add AppSync runtime globals
    const appsyncGlobals = `// AppSync runtime globals
declare const util: {
  error: (message: string, errorType?: string, data?: unknown, errorInfo?: unknown) => never;
  appendError: (message: string, errorType?: string, data?: unknown, errorInfo?: unknown) => void;
  autoId: () => string;
  time: {
    nowISO8601: () => string;
    nowEpochSeconds: () => number;
    nowEpochMilliSeconds: () => number;
    nowFormatted: (format: string, timezone?: string) => string;
    parseFormattedToEpochMilliSeconds: (time: string, format: string, timezone?: string) => number;
    parseISO8601ToEpochMilliSeconds: (time: string) => number;
    epochMilliSecondsToSeconds: (epoch: number) => number;
    epochMilliSecondsToISO8601: (epoch: number) => string;
    epochMilliSecondsToFormatted: (epoch: number, format: string, timezone?: string) => string;
  };
  dynamodb: {
    toDynamoDB: (value: unknown) => Record<string, unknown>;
    toMapValues: (values: Record<string, unknown>) => Record<string, unknown>;
    toS3Object: (key: string, bucket: string, region: string, version?: string) => unknown;
  };
  transform: {
    toDynamoDBFilterExpression: (filter: unknown) => unknown;
  };
  str: {
    toUpper: (str: string) => string;
    toLower: (str: string) => string;
    toReplace: (str: string, substr: string, newSubstr: string) => string;
    normalize: (str: string, form: string) => string;
  };
  math: {
    roundNum: (num: number) => number;
    minVal: (nums: number[]) => number;
    maxVal: (nums: number[]) => number;
    randomDouble: () => number;
    randomWithSeed: (seed: number) => number;
  };
  authType: () => string;
};
declare const runtime: {
  earlyReturn: (result: unknown) => never;
};
interface ContextIdentity {
  sub: string;
  issuer: string;
  username: string;
  claims: Record<string, unknown>;
  sourceIp: string[];
  defaultAuthStrategy: string;
  groups: string[] | null;
}
type Context<TArguments = Record<string, unknown>, TSource = Record<string, unknown> | null, TStash = Record<string, unknown>, TResult = any, TReturns = unknown> = {
  arguments: TArguments;
  args: TArguments;
  source: TSource;
  result: TResult;
  prev: { result: TReturns } | null;
  stash: TStash;
  identity: ContextIdentity | null;
  request: { headers: Record<string, string>; domainName: string | null };
  info: { fieldName: string; parentTypeName: string; variables: Record<string, unknown>; selectionSetList: string[]; selectionSetGraphQL: string };
  env: Record<string, string>;
  error: { message: string; type: string } | null;
};
type AppSyncIdentityCognito = ContextIdentity;

`;
    codeToCompile = appsyncGlobals + codeToCompile;

    // Inject table name
    if (codeToCompile.includes("ctx.env.TABLE_NAME")) {
      codeToCompile = codeToCompile.replace(
        /ctx\.env\.TABLE_NAME/g,
        `"${this.tableName}"`
      );
    }
    if (codeToCompile.includes("__INJECTED_TABLE_NAME__")) {
      codeToCompile = codeToCompile.replace(
        /"__INJECTED_TABLE_NAME__"/g,
        `"${this.tableName}"`
      );
      codeToCompile = codeToCompile.replace(
        /__INJECTED_TABLE_NAME__/g,
        `"${this.tableName}"`
      );
    }

    // Write prepared source to build directory
    const tempResolverPath = path.join(this.buildDir, resolverRelativePath);
    await fsPromises.mkdir(path.dirname(tempResolverPath), {
      recursive: true,
    });
    await fsPromises.writeFile(tempResolverPath, codeToCompile);
  }

  /**
   * Compile all resolvers with TypeScript
   */
  private async compileAllResolvers(): Promise<void> {
    this.logger.info("Compiling all resolvers with TypeScript...");

    const distDir = path.join(this.buildDir, "dist");
    await fsPromises.mkdir(distDir, { recursive: true });

    try {
      const { exec } = await import("child_process");
      const { promisify } = await import("util");
      const execAsync = promisify(exec);

      await execAsync("yarn tsc -p tsconfig.json", { cwd: this.buildDir });
      this.logger.info("All resolvers compiled successfully");
    } catch (error: unknown) {
      const err = error as ExecError;
      const stdout = err.stdout?.toString() || "";
      const hasSyntaxError =
        stdout.includes("SyntaxError") ||
        stdout.includes("Cannot find module");

      if (hasSyntaxError) {
        this.logger.error(`TypeScript compilation failed with syntax errors:`);
        this.logger.error(stdout);
        throw error;
      }

      // Type errors - JS still emitted, just warn
      this.logger.warning(`TypeScript reported type errors (JS still emitted)`);
      const lines = stdout.split("\n").filter((l) => l.includes("error TS"));
      if (lines.length > 0) {
        const preview = lines.slice(0, 5).join("\n  ");
        this.logger.debug(preview);
        if (lines.length > 5) {
          this.logger.debug(`... and ${lines.length - 5} more type errors`);
        }
      }
    }
  }

  /**
   * Main entry point: compile and upload all resolvers
   *
   * @returns Build hash (used in CloudFormation parameters)
   */
  public async compileAndUploadResolvers(): Promise<string> {
    this.logger.info("Setting up build directory...");
    await this.setupBuildDirectory();

    // Discover resolvers if not provided
    if (this.resolverFiles.length === 0) {
      await this.discoverResolverFiles();
    }

    const totalFiles = this.resolverFiles.length;
    this.logger.info(`Found ${totalFiles} resolver files`);

    const localSavePathBase = path.join(
      this.projectRoot,
      ".cache",
      "deploy",
      "resolvers"
    );

    const failedResolvers: { file: string; error: string }[] = [];
    const compiledFilesRelative: string[] = [];
    const resolverSourcePaths: { relative: string; absolute: string }[] = [];

    const baseResolverDir = path.join(this.projectRoot, "backend", "resolvers");

    // Phase 1: Prepare source files
    for (const resolverFileRelativePath of this.resolverFiles) {
      const resolverAbsolutePath = path.join(
        baseResolverDir,
        resolverFileRelativePath
      );

      try {
        const originalCode = await fsPromises.readFile(
          resolverAbsolutePath,
          "utf-8"
        );
        await this.prepareSourceFile(originalCode, resolverAbsolutePath);
        resolverSourcePaths.push({
          relative: resolverFileRelativePath,
          absolute: resolverAbsolutePath,
        });
      } catch (error: unknown) {
        const err = error as ExecError;
        failedResolvers.push({
          file: resolverFileRelativePath,
          error: err.message || String(error),
        });
      }
    }

    // Phase 2: Compile all
    try {
      await this.compileAllResolvers();
    } catch (error: unknown) {
      const err = error as ExecError;
      for (const resolver of resolverSourcePaths) {
        failedResolvers.push({
          file: resolver.relative,
          error: `Batch compilation failed: ${err.message || String(error)}`,
        });
      }
    }

    // Phase 3: Read compiled files
    for (const resolver of resolverSourcePaths) {
      try {
        const compiledJsPath = path.join(
          this.buildDir,
          "dist",
          resolver.relative.replace(".ts", ".js")
        );
        let jsContent = await fsPromises.readFile(compiledJsPath, "utf-8");
        jsContent = this.addHeaderToJs(jsContent, resolver.absolute);

        const localSavePath = path.join(
          localSavePathBase,
          resolver.relative.replace(".ts", ".js")
        );
        await fsPromises.mkdir(path.dirname(localSavePath), {
          recursive: true,
        });
        await fsPromises.writeFile(localSavePath, jsContent);

        compiledFilesRelative.push(resolver.relative.replace(".ts", ".js"));
        this.logger.debug(`Compiled: ${path.basename(resolver.relative)}`);
      } catch (error: unknown) {
        const err = error as ExecError;
        failedResolvers.push({
          file: resolver.relative,
          error: err.message || String(error),
        });
      }
    }

    // Compute build hash
    const contents: string[] = [];
    compiledFilesRelative.sort();
    for (const relPath of compiledFilesRelative) {
      const localFile = path.join(localSavePathBase, relPath);
      const buf = await fsPromises.readFile(localFile, "utf-8");
      contents.push(buf);
    }
    const hasher = crypto.createHash("sha256");
    for (const c of contents) hasher.update(c);
    const buildHash = hasher.digest("hex").slice(0, 16);
    this.logger.info(`Build hash: ${buildHash}`);

    // Validate with AppSync (parallel with concurrency limit)
    this.logger.info("Validating resolvers with AppSync...");
    const failedValidations: { file: string; error: string }[] = [];
    const concurrencyLimit = 10; // Validate 10 resolvers in parallel
    let validatedCount = 0;
    const totalToValidate = compiledFilesRelative.length;

    // Process in batches
    for (let i = 0; i < compiledFilesRelative.length; i += concurrencyLimit) {
      const batch = compiledFilesRelative.slice(i, i + concurrencyLimit);

      const batchPromises = batch.map(async (relPath) => {
        const localPath = path.join(localSavePathBase, relPath);
        try {
          const content = await fsPromises.readFile(localPath, "utf-8");
          await this.validateWithAppSync(content, relPath);
          return { success: true, file: relPath };
        } catch (err: unknown) {
          const errorMessage = err instanceof Error ? err.message : String(err);
          return { success: false, file: relPath, error: errorMessage };
        }
      });

      const results = await Promise.all(batchPromises);

      for (const result of results) {
        validatedCount++;
        if (!result.success && result.error) {
          failedValidations.push({ file: result.file, error: result.error });
        }
      }

      // Show progress
      process.stdout.write(
        `\r  Validated ${validatedCount}/${totalToValidate} resolvers...`
      );
    }

    console.log(""); // New line after progress

    if (failedValidations.length > 0) {
      this.logger.error(
        `${failedValidations.length} resolver(s) failed validation:`
      );
      failedValidations.forEach(({ file, error }) => {
        this.logger.error(`  - ${file}: ${error}`);
      });
      throw new Error(
        `${failedValidations.length} resolver(s) failed AppSync validation.`
      );
    }
    this.logger.success(
      `All ${compiledFilesRelative.length} resolvers passed validation`
    );

    // Upload to S3 (parallel with progress)
    this.logger.info("Uploading resolvers to S3...");
    const uploadBatchSize = 10;
    let uploadedCount = 0;
    const totalUploads = compiledFilesRelative.length;

    for (let i = 0; i < compiledFilesRelative.length; i += uploadBatchSize) {
      const batch = compiledFilesRelative.slice(i, i + uploadBatchSize);

      await Promise.all(
        batch.map(async (relPath) => {
          const s3Key = path.posix.join(
            this.s3KeyPrefix,
            this.stage,
            buildHash,
            relPath
          );
          const localPath = path.join(localSavePathBase, relPath);
          const content = await fsPromises.readFile(localPath, "utf-8");
          await this.uploadToS3(s3Key, content, "application/javascript");
        })
      );

      uploadedCount += batch.length;
      process.stdout.write(
        `\r  Uploaded ${uploadedCount}/${totalUploads} resolvers...`
      );
    }
    console.log(""); // New line after progress

    if (failedResolvers.length > 0) {
      this.logger.error(
        `Failed to compile ${failedResolvers.length} resolver(s)`
      );
      failedResolvers.forEach(({ file, error }) => {
        this.logger.error(`  - ${file}: ${error}`);
      });
      throw new Error(
        `Failed to compile ${failedResolvers.length} resolver(s).`
      );
    }

    this.logger.success(
      `${compiledFilesRelative.length} resolvers compiled and uploaded`
    );

    await this.cleanupOldS3Resolvers(2);

    return buildHash;
  }
}
